# Generated by Django 5.1 on 2024-08-30 22:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_prospect', models.BooleanField(default=True)),
                ('qtd_cars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('gray', 'Gray')], max_length=10)),
                ('model', models.CharField(choices=[('hatch', 'Hatch'), ('sedan', 'Sedan'), ('convertible', 'Convertible')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carford.owner')),
            ],
        ),
    ]
